<?php

namespace App\Shared\Enums;

class EventType
{
  const TRANSACTION_AUTHORIZED = 'TRANSACTION_AUTHORIZED';
  const TRANSACTION_NOT_AUTHORIZED = 'TRANSACTION_NOT_AUTHORIZED';
  const TRANSACTION_PAID = 'TRANSACTION_PAID';
  const TRANSACTION_NOT_PAID = 'TRANSACTION_NOT_PAID';
  const TRANSACTION_NOTIFIED = 'TRANSACTION_NOTIFIED';
  const TRANSACTION_NOT_NOTIFIED = 'TRANSACTION_NOT_NOTIFIED';
}